### ISSUE TITLE
Add Audio trimmer functionality

### ISSUE THREAD

**Issue by JEN14dobariya** [Dimowner/AudioRecorder#60] opened 2021-05-10 21:53 UTC
I think having audio trimmer functionality will be good so user can trim some noise from sound themselves.

**Comment by ueen** [comment] 2021-05-31 11:46
That's the only feature I'm missing to fully replace Googles recorder :)

**Comment by yephny** [comment] 2021-12-22 15:30
Duplicate of #28.

**Closed** 2021-12-23 07:09 UTC
